# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580b674c3c1bcb35e72bff8451481e6ba7a1f6baa391ed6908c7ca47323b7b7e07a6252855723bfad44f7d7bcdcbe4a758e39874b96b2397321dc2b8e2e62ac7

test:
  secret_key_base: d5dc45ea15989191b01f18d6625e81f7757e7a79b3e8236e2de36b5602211784fc254614e5273c1c0fefeccf47a0275b31d9cf6d9e74df91220c8a358cfe01c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
